version: "3"
services:
  apache:
    build: ./apache
    volumes:
      - ${HOST_CODE_PATH}:${CONTAINER_CODE_PATH}
    ports:
      - "80:80"
  php-fpm:
    build:
      context: ./php-fpm
      args:
        PHP_VERSION: ${PHP_VERSION}
    volumes:
      - ${HOST_CODE_PATH}:${CONTAINER_CODE_PATH}
    expose:
      - 9000